version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    ports:
      - "5432:5432"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
